-- MySQL Script generated by MySQL Workbench
-- 11/27/14 23:51:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sesa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sesa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sesa` DEFAULT CHARACTER SET utf8 ;
USE `sesa` ;

-- -----------------------------------------------------
-- Table `sesa`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesa`.`evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario` VARCHAR(70) NULL DEFAULT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `ponto` INT(11) NOT NULL,
  `dtFim` DATE NOT NULL,
  `dtIncio` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sesa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesa`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `tpUsuario` VARCHAR(45) NOT NULL,
  `pontosu` INT(11) NULL DEFAULT '0',
  `dataNasc` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_692bsnqxa8m9fmx7m1yc6hsui` (`cpf` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sesa`.`ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesa`.`ranking` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idEvento` INT(11) NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_k42kbih1kj6cxtvhixe6bh7bx` (`idEvento` ASC),
  INDEX `FK_3415my3bgtjf9c5chn8rp07yt` (`idUsuario` ASC),
  CONSTRAINT `FK_3415my3bgtjf9c5chn8rp07yt`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sesa`.`usuario` (`id`),
  CONSTRAINT `FK_k42kbih1kj6cxtvhixe6bh7bx`
    FOREIGN KEY (`idEvento`)
    REFERENCES `sesa`.`evento` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `sesa`;

DELIMITER $$
USE `sesa`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `sesa`.`AI_UPONTOS`
BEFORE INSERT ON `sesa`.`usuario`
FOR EACH ROW
begin
set new.pontosu = 0;
end$$


DELIMITER ;
